name: CI
on: [push, pull_request]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create
        run: |
          cat staticFile > indexTmp.html
          cat indexTmp.html
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: indexTmp
          path: indexTmp.html
          retention-days: 1
  Deploy:
    name: Deploy
    if: ${{ success() }} && github.ref == 'refs/heads/main'   # Deploy only from mai
    needs: [Build]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
    permissions:
      contents: write  # Add to push to a branch
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List
        run: |
          ls -la
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: indexTmp
          path: .
      - name: List After
        run: |
          ls -la
      - name: Upload
        run: |
          git config user.email "githubaction@users.noreply.github.com"
          git config user.name "GitHub Action"
          git fetch   # Fetch branches
          git checkout gh-pages
          rm -rf index.html
          mv indexTmp.html index.html
          git add index.html
          git commit --amend -m "Deploy from ${{ github.sha }}" # Overwrite since the history is not needed for generated files
          git push --force

