name: CI
on: [push, pull_request]
jobs:
  Verification:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux",
            os: ubuntu-latest
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cat staticFile > indexTmp.html
          cat indexTmp.html
      - name: Deploy
      if: github.ref == 'refs/heads/main'
        run: |
          git checkout gh-pages
          rm -rf index.html
          mv indexTemp.html index.html
          git add index.html
          git commit --amend -m "Deploy from ${{ github.sha }}"
          git push --force
